<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { toast } from 'vue3-toastify';
import Toolbar from '@/components/Toolbar.vue';
import Grid from '@/components/Grid.vue';
import GridPagination from '@/components/GridPagination.vue';
import HiddenQueryFieldAlertInfo from '@/components/HiddenQueryFieldAlertInfo.vue';
import { getGridConfig, resetConfigByOld, setConfigPage, setConfigRow, setConfigTotal } from '@/components/GridHelper';
import { escapeQifuHtmlMsg, getAxiosInstance } from '@/components/BaseHelper';
import { useSwalLoading } from '@/composables/useSwalLoading';
import { useMdProg010d0004Store } from './QueryPageStore';
import { PageConstants, insightTypeOptions, sourceTypeOptions, severityOptions, statusOptions } from './config';

definePageMeta({ middleware: ['auth'] });

const queryPageStore = useMdProg010d0004Store();
const { showLoading, hideLoading, confirmFire } = useSwalLoading();
const pageProgramId = ref(PageConstants.QueryId);
const qFieldShow = ref(true);
const dsList = ref<any[]>([]);
const selectedInsight = ref<any>(null);

const isSearchNoData = (message: any) => String(message || '').toLowerCase().includes('search no data');
const dateText = (value: any) => value ? new Date(value).toLocaleString() : '-';
const badgeHtml = (value: string, style: string) => `<span class="badge ${style}">${value || '-'}</span>`;
const severityHtml = (value: string) => {
    const style = value === 'CRITICAL' || value === 'HIGH' ? 'text-bg-danger' : value === 'MEDIUM' ? 'text-bg-warning' : 'text-bg-success';
    return badgeHtml(value, style);
};
const statusHtml = (value: string) => {
    const style = value === 'OPEN' ? 'text-bg-warning' : value === 'ACCEPTED' ? 'text-bg-primary' : value === 'RESOLVED' ? 'text-bg-success' : 'text-bg-secondary';
    return badgeHtml(value, style);
};

const clearGridConfig = () => {
    setConfigRow(queryPageStore.gridConfig, import.meta.env.VITE_DEFAULT_ROW);
    setConfigPage(queryPageStore.gridConfig, 1);
    setConfigTotal(queryPageStore.gridConfig, 0);
};

const loadInsight = async (oid: string) => {
    showLoading();
    try {
        const response = await getAxiosInstance().post(import.meta.env.VITE_API_URL + PageConstants.eventNamespace + '/load', { oid });
        if (response.data?.success !== import.meta.env.VITE_SUCCESS_FLAG) throw new Error(response.data?.message || 'Load failed');
        selectedInsight.value = response.data.value;
    } catch (e: any) {
        toast.warning(escapeQifuHtmlMsg(e?.message || String(e)));
    } finally {
        hideLoading();
    }
};

const changeStatus = async (payload: { endpoint: string, oid: string, message: string }) => {
    showLoading();
    try {
        const response = await getAxiosInstance().post(import.meta.env.VITE_API_URL + PageConstants.eventNamespace + payload.endpoint, { oid: payload.oid });
        if (response.data?.success !== import.meta.env.VITE_SUCCESS_FLAG) throw new Error(response.data?.message || 'Update failed');
        toast.success(payload.message);
        selectedInsight.value = response.data.value;
        await btnQuery();
    } catch (e: any) {
        toast.warning(escapeQifuHtmlMsg(e?.message || String(e)));
    } finally {
        hideLoading();
    }
};

const acceptInsight = (oid: string) => confirmFire('Accept this insight?', changeStatus, { endpoint: '/accept', oid, message: 'Insight accepted' });
const dismissInsight = (oid: string) => confirmFire('Dismiss this insight?', changeStatus, { endpoint: '/dismiss', oid, message: 'Insight dismissed' });
const resolveInsight = (oid: string) => confirmFire('Resolve this insight?', changeStatus, { endpoint: '/resolve', oid, message: 'Insight resolved' });

const initGridConfig = () => getGridConfig('oid', [
    { method: loadInsight, icon: 'eye', type: 'view', memo: 'View insight detail.', class: 'btn btn-outline-primary btn-sm' },
    { method: acceptInsight, icon: 'check2-circle', type: 'accept', memo: 'Accept insight.', class: 'btn btn-outline-success btn-sm' },
    { method: dismissInsight, icon: 'x-circle', type: 'dismiss', memo: 'Dismiss insight.', class: 'btn btn-outline-secondary btn-sm' },
    { method: resolveInsight, icon: 'flag', type: 'resolve', memo: 'Resolve insight.', class: 'btn btn-outline-info btn-sm' }
], [
    { label: 'Actions', field: 'oid', textAlign: 'center', labTextAlign: 'center' },
    { label: 'Insight No', field: 'insightNo' },
    { label: 'Title', field: 'title' },
    { label: 'Type', field: 'insightType' },
    { label: 'Source', field: 'sourceType', textAlign: 'center' },
    { label: 'Severity', field: 'severity', colMethod: severityHtml, colHtml: true, textAlign: 'center' },
    { label: 'Status', field: 'status', colMethod: statusHtml, colHtml: true, textAlign: 'center' },
    { label: 'Owner', field: 'ownerAccount' },
    { label: 'Generated By', field: 'generatedByType', textAlign: 'center' },
    { label: 'Generated', field: 'generatedAt', colMethod: dateText }
]);

const btnQuery = async () => {
    showLoading();
    dsList.value = [];
    try {
        const response = await getAxiosInstance().post(import.meta.env.VITE_API_URL + PageConstants.eventNamespace + '/findPage', {
            field: {
                insightNoLike: queryPageStore.queryParam.insightNo,
                titleLike: queryPageStore.queryParam.title,
                insightType: queryPageStore.queryParam.insightType,
                severity: queryPageStore.queryParam.severity,
                sourceType: queryPageStore.queryParam.sourceType,
                status: queryPageStore.queryParam.status,
                ownerAccount: queryPageStore.queryParam.ownerAccount,
                generatedByType: queryPageStore.queryParam.generatedByType
            },
            pageOf: { select: queryPageStore.gridConfig.page, showRow: queryPageStore.gridConfig.row }
        });
        if (response.data?.success !== import.meta.env.VITE_SUCCESS_FLAG) {
            clearGridConfig();
            if (isSearchNoData(response.data?.message)) return;
            throw new Error(response.data?.message || 'Query failed');
        }
        dsList.value = response.data.value || [];
        setConfigTotal(queryPageStore.gridConfig, response.data.pageOf?.countSize || dsList.value.length);
    } catch (e: any) {
        clearGridConfig();
        toast.warning(escapeQifuHtmlMsg(e?.message || String(e)));
    } finally {
        hideLoading();
    }
};

const btnClear = () => {
    queryPageStore.clearData();
    dsList.value = [];
    selectedInsight.value = null;
    clearGridConfig();
};
const changeGridRow = (row: number) => { setConfigRow(queryPageStore.gridConfig, row); queryPageStore.gridConfig.page = 1; btnQuery(); };
const changePage = (page: number) => { setConfigPage(queryPageStore.gridConfig, page); btnQuery(); };

onMounted(() => {
    const config = initGridConfig();
    if (queryPageStore.gridConfig.column) resetConfigByOld(config, queryPageStore.gridConfig);
    queryPageStore.gridConfig = config;
    if (queryPageStore.gridConfig.total > 0) btnQuery();
});
</script>

<template>
  <Toolbar :progId="pageProgramId" description="Insight Inbox" refreshFlag="Y" @refreshMethod="btnQuery"
           queryFieldShowSwitchFlag="Y" @queryFieldShowSwitcMethod="qFieldShow = !qFieldShow" />
  <HiddenQueryFieldAlertInfo :dataSource="dsList" :queryFieldShowFlag="qFieldShow" />

  <div v-show="qFieldShow" class="card mb-3">
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-2"><input class="form-control" placeholder="Insight no" v-model="queryPageStore.queryParam.insightNo"></div>
        <div class="col-md-3"><input class="form-control" placeholder="Title" v-model="queryPageStore.queryParam.title"></div>
        <div class="col-md-2"><select class="form-select" v-model="queryPageStore.queryParam.insightType"><option v-for="item in insightTypeOptions" :key="item.value" :value="item.value">{{ item.label }}</option></select></div>
        <div class="col-md-2"><select class="form-select" v-model="queryPageStore.queryParam.sourceType"><option v-for="item in sourceTypeOptions" :key="item.value" :value="item.value">{{ item.label }}</option></select></div>
        <div class="col-md-2"><select class="form-select" v-model="queryPageStore.queryParam.severity"><option v-for="item in severityOptions" :key="item.value" :value="item.value">{{ item.label }}</option></select></div>
        <div class="col-md-2"><select class="form-select" v-model="queryPageStore.queryParam.status"><option v-for="item in statusOptions" :key="item.value" :value="item.value">{{ item.label }}</option></select></div>
        <div class="col-md-2"><input class="form-control" placeholder="Owner" v-model="queryPageStore.queryParam.ownerAccount"></div>
        <div class="col-md-2"><select class="form-select" v-model="queryPageStore.queryParam.generatedByType"><option value="">All generated</option><option value="RULE">Rule</option><option value="LLM">LLM</option><option value="MANUAL">Manual</option></select></div>
        <div class="col-md-3 d-flex gap-2"><button class="btn btn-primary" @click="btnQuery"><i class="bi bi-search"></i> Query</button><button class="btn btn-outline-secondary" @click="btnClear"><i class="bi bi-eraser"></i></button></div>
      </div>
    </div>
  </div>

  <div v-if="selectedInsight" class="card mb-3 border-primary-subtle">
    <div class="card-header d-flex justify-content-between align-items-center">
      <span>{{ selectedInsight.insightNo }} - {{ selectedInsight.title }}</span>
      <button class="btn btn-outline-secondary btn-sm" @click="selectedInsight = null"><i class="bi bi-x-lg"></i></button>
    </div>
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-2"><strong>Severity</strong><div v-html="severityHtml(selectedInsight.severity)"></div></div>
        <div class="col-md-2"><strong>Status</strong><div v-html="statusHtml(selectedInsight.status)"></div></div>
        <div class="col-md-2"><strong>Source</strong><div>{{ selectedInsight.sourceType }}</div></div>
        <div class="col-md-3"><strong>Owner</strong><div>{{ selectedInsight.ownerAccount || '-' }}</div></div>
        <div class="col-md-3"><strong>Generated</strong><div>{{ dateText(selectedInsight.generatedAt) }}</div></div>
        <div class="col-12"><strong>Summary</strong><div class="border rounded p-2 bg-light">{{ selectedInsight.summaryText || '-' }}</div></div>
        <div class="col-md-6"><strong>Signal OID</strong><div class="text-break">{{ selectedInsight.signalOid || '-' }}</div></div>
        <div class="col-md-6"><strong>Rule OID</strong><div class="text-break">{{ selectedInsight.ruleOid || '-' }}</div></div>
      </div>
    </div>
  </div>

  <GridPagination :progId="pageProgramId" :gridConfig="queryPageStore.gridConfig"
                  :changePageSelectMethod="changePage" :changeGridConfigRowMethod="changeGridRow" />
  <Grid :progId="pageProgramId" :dataSource="dsList" :config="queryPageStore.gridConfig" />
  <div v-if="dsList.length === 0" class="text-center text-muted py-3">No insights</div>
</template>
